services:
  elasticsearch:
    image: elasticsearch:7.10.1

    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.10.1

    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
