apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app-deployment
spec:
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth-app-container
          image: hoangdat12/auth-service
          resources:
            # limits:
            #   memory: "128Mi"
            #   cpu: "500m"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-app-service
spec:
  selector:
    app: auth-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
