apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-app-deployment
spec:
  selector:
    matchLabels:
      app: cart-app
  template:
    metadata:
      labels:
        app: cart-app
    spec:
      containers:
        - name: cart-app-container
          image: hoangdat12/cart-service
          resources:
            # limits:
            #   memory: "128Mi"
            #   cpu: "500m"
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: cart-app-service
spec:
  selector:
    app: cart-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
