apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-app-deployment
spec:
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
        - name: gateway-app-container
          image: hoangdat12/api-gateway
          resources:
            # limits:
            #   memory: "128Mi"
            #   cpu: "500m"
          ports:
            - containerPort: 5000
          env:
            - name: AUTH_APP
              value: auth-app-service
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-app-service
spec:
  selector:
    app: gateway-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
