apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app-deployment
spec:
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
        - name: order-app-container
          image: hoangdat12/order-service
          resources:
            # limits:
            #   memory: "128Mi"
            #   cpu: "500m"
          ports:
            - containerPort: 8086
          env:
            - name: PORT
              value: '8086'
---
apiVersion: v1
kind: Service
metadata:
  name: order-app-service
spec:
  selector:
    app: order-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
