apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app-deployment
spec:
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: product-app-container
          image: hoangdat12/product-service
          resources:
            # limits:
            #   memory: "128Mi"
            #   cpu: "500m"
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: '8081'
            - name: SECRET_ACCESS_KEY
              value: '58703273357638792F423F4528482B4D6251655468566D597133743677397A24'
            - name: SECRET_REFRESH_KEY
              value: '7538782F413F4428472B4B6250655367566B5970337336763979244226452948'
            - name: SECRET_KEY_EMAIL
              value: 'tfawqbegelpeykdv'
            - name: EMAIL
              value: 'datttp113@gmail.com'
---
apiVersion: v1
kind: Service
metadata:
  name: product-app-service
spec:
  selector:
    app: product-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
